import type { QaSpec } from "./types";

/**
 * What PROF. ROHIT says in the Lab. Visitors pick a topic or type a
 * question; the topic whose keywords match best answers. Keep answers short
 * and let `then` open the screen with the full details.
 */
export const professorQa: QaSpec = {
  greeting: ["I'm PROF. {name}. Ask me anything about my work!"],
  topics: [
    {
      label: "Current role",
      keywords: [
        "ust",
        "job",
        "work",
        "current",
        "currently",
        "developer",
        "company",
        "employer",
        "doing",
        "modernization",
        "modernisation",
        "legacy",
        "as400",
        "retail",
        "workshop",
        "migration",
      ],
      answer: [
        "I'm an AI Engineer at UST in Chennai.",
        "I modernize a Fortune 500 retailer's AS400/IBM i apps to Next.js with custom agentic workflows.",
      ],
      then: { screen: "party", job: "ust" },
    },
    {
      label: "Agents & AI",
      keywords: [
        "agent",
        "agents",
        "agentic",
        "ai",
        "llm",
        "llms",
        "orchestration",
        "workflow",
        "workflows",
        "rag",
        "retrieval",
        "genai",
        "generative",
        "model",
        "models",
      ],
      answer: [
        "Agents are my specialty: orchestration, sub-agents, validation and approval-aware workflows.",
        "SOVEREIGN even runs agents on local LLMs behind permission boundaries.",
      ],
      then: { screen: "dex", project: "ai-factory" },
    },
    {
      label: "Projects",
      keywords: [
        "project",
        "projects",
        "built",
        "build",
        "building",
        "portfolio",
        "factory",
        "portal",
        "mnemo",
        "sovereign",
        "side",
        "made",
      ],
      answer: [
        "I've worked on AI FACTORY, AI PORTAL, MNEMO and SOVEREIGN.",
        "Each one has a machine here in the LAB. Here's the POKéDEX!",
      ],
      then: { screen: "dex" },
    },
    {
      label: "Skills",
      keywords: [
        "skill",
        "skills",
        "stack",
        "tech",
        "technology",
        "technologies",
        "react",
        "next",
        "nextjs",
        "java",
        "spring",
        "python",
        "flask",
        "node",
        "typescript",
        "javascript",
        "database",
        "databases",
        "sql",
        "frontend",
        "backend",
        "aws",
      ],
      answer: [
        "Full-stack: React, Next.js and TypeScript up front; Java/Spring Boot, Node and Python/Flask behind.",
        "The POKé MART sells them all as TMs!",
      ],
      then: { screen: "bag" },
    },
    {
      label: "Education",
      keywords: [
        "education",
        "degree",
        "college",
        "university",
        "study",
        "studied",
        "btech",
        "graduate",
        "graduated",
        "ielts",
        "english",
        "certification",
        "certifications",
      ],
      answer: [
        "I studied Computer Science and Engineering at Providence College of Engineering.",
        "I also scored 7.5 overall in IELTS Academic.",
      ],
      then: { screen: "card" },
    },
    {
      label: "Relocation",
      keywords: [
        "relocate",
        "relocation",
        "move",
        "moving",
        "location",
        "where",
        "based",
        "chennai",
        "india",
        "remote",
        "abroad",
        "country",
        "live",
      ],
      answer: ["I'm based in Chennai, India, and I'm open to relocation!"],
      then: { screen: "jobs" },
    },
    {
      label: "Hiring",
      keywords: [
        "hire",
        "hiring",
        "available",
        "availability",
        "open",
        "roles",
        "opportunity",
        "opportunities",
        "position",
        "positions",
        "looking",
        "vacancy",
      ],
      answer: [
        "I'm open to AI engineering and software engineering roles.",
        "The JOB BOARD has the full list. Or catch me in the tall grass!",
      ],
      then: { screen: "jobs" },
    },
    {
      label: "Contact",
      keywords: [
        "contact",
        "email",
        "mail",
        "linkedin",
        "github",
        "reach",
        "message",
        "call",
        "phone",
        "connect",
      ],
      answer: ["Here's how to reach me!"],
      then: { screen: "contact" },
    },
  ],
  fallback: [
    "Hmm, I don't have notes on that!",
    "Try asking about my projects, skills, experience, or how to contact me.",
  ],
};
